apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elastic.nameref }}
spec:
  version: {{ .Chart.AppVersion }}
  nodeSets:
  - name: master
    count: {{ .Values.elastic.master.replicas }}
    config:
      node.roles:
        - master
      node.store.allow_mmap: false
    podTemplate:
      {{- toYaml .Values.elastic.master.podTemplate | nindent 6 }}
  - name: cold
    count: {{ .Values.elastic.cold.replicas }}
    config:
      node.roles:
        - data
      node.store.allow_mmap: false
    podTemplate:
      {{- toYaml .Values.elastic.cold.podTemplate | nindent 6 }}
