apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  configuration:
    {{- if .Values.zookeeper }}
    zookeeper:
      nodes:
      {{- with .Values.zookeeper }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}

    clusters:
      - name: {{ .Values.clusterName }}
        templates:
          podTemplate: pod-template-with-volumes
        layout:
          shardsCount: {{ .Values.shardsCount }}
          replicasCount: {{ .Values.replicasCount }}
    users:
      {{- range .Values.users }}
      {{ .username }}/password: {{ .password }}
      {{ .username }}/profile: {{ .profile }}
      {{ .username }}/networks/ip:
        {{- range $network := .networks }}
        - {{ $network }}
        {{- end }}
      {{- end }}

  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: clickhouse
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}

              resources:
                {{- toYaml .Values.resources | nindent 16 }}
 
            {{- with .Values.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
            {{- end }}

        {{- with .Values.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
        {{- end }}
  {{- with .Values.volumeClaimTemplates }}
    volumeClaimTemplates:
      {{- toYaml . | nindent 6 }}
  {{- end }}
