{{ if .Values.out }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      k8s:selector.cilium.rbkmoney/release: {{ .Release.Name }}
  egress:
  {{- range .Values.out }}
  - toEndpoints:
    - matchLabels:
        k8s:selector.cilium.rbkmoney/release: {{ .name }}
    toPorts:
      - ports:
    {{- range .filters }}
        - protocol: {{ .type }}
          port: {{ .port }}
    {{- end }}
  {{- end }}
{{- end }}
