{{ if .Values.EgressCiliumPolicy }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      k8s:selector.cilium.rbkmoney/release: {{ .Release.Name }}
  egress:
  {{- range .Values.EgressCiliumPolicy }}
  {{- if .release }}
  - toEndpoints:
    - matchLabels:
        k8s:selector.cilium.rbkmoney/release: {{ .release }}
  {{- else if .FQDNs }}
  - toFQDNs:
    {{- range .FQDNs }}
    - matchName: "{{ . }}"
    {{- end }}
  {{- end }}
    toPorts:
      - ports:
    {{- range .filters }}
        - protocol: {{ .type }}
          port: {{ .port | quote }}
    {{- end }}
  {{- end }}
{{- end }}
