---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: icmp-allow
  namespace: {{ .Values.processingNamespace }}
specs:
  - endpointSelector:
      matchLabels:
        k8s:io.kubernetes.pod.namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
    ingress:
    - fromEntities:
        - world
      icmps:
      - fields:
        - type: 136
          family: IPv6
    egress:
    - toEntities:
        - world
      icmps:
      - fields:
        - type: 136
          family: IPv6