---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-intra-zookeeper"
  namespace: {{ .Values.processingNamespace | default .Release.Namespace }}
specs:
  - endpointSelector:
      matchLabels:
        k8s:app.kubernetes.io/name: zookeeper
    ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:app.kubernetes.io/name: zookeeper 
      toPorts:
      - ports:
        - port: "2181"
          protocol: TCP
        - port: "2888"
          protocol: TCP
        - port: "3888"
          protocol: TCP
    - fromEntities:
      - remote-node
  - endpointSelector:
      matchLabels:
        k8s:app.kubernetes.io/name: zookeeper
    egress:
    - toEndpoints:
      - matchLabels:
          k8s:app.kubernetes.io/name: zookeeper
      toPorts:
      - ports:
        - port: "2181"
          protocol: TCP
        - port: "2888"
          protocol: TCP
        - port: "3888"
          protocol: TCP
